mining_folketinget/query_folketinget/urls.py
from django.conf.urls import patterns, url

from query_folketinget import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index')
)

mining_folketinget/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mining_folketinget.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
		url(r'^query_folketinget/', include('query_folketinget.urls', namespace='query_folketinget')),
    url(r'^admin/', include(admin.site.urls)),
)

query_folketinget/urls.py
from django.conf.urls import patterns, url

from query_folketinget import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^predict', views.predict, name='predict'),
)

query_folketinget/models.py
from django.db import models

# Create your models here.

query_folketinget/views.py
# -*- coding: utf-8 -*-
from __future__ import division
from django.shortcuts import render
from django.http import HttpResponse
import resume_lda
import HTMLParser
import numpy as np
from django.views.decorators.csrf import csrf_protect
from django.template.loader import render_to_string
from scipy import stats
import math
import utils
import os
import json


def index(request):
    """Renders the frontpage
    """
    return render(request, 'query_folketinget/index.html')


@csrf_protect
def predict(request):
    """Predicts the votes of danish politicians based on decision tree classifiers.
    """
    html_parser = HTMLParser.HTMLParser()
    parties = [
        'Venstre', 'Socialdemokratiet', 'Socialistisk Folkeparti',
        'Dansk Folkeparti', 'Radikale Venstre', 'Enhedslisten',
        'Liberal Alliance', 'Det Konservative Folkeparti'
    ]
    categories = [
        u'Beretning af almen art', u'Alm. del', u'FT',
        u'Henvendelser uden bilagsnummer',
        u'Mødesag', u'Info-noter', u'US', u'Alm. del §-markeret',
        u'EU-noter',
        u'B1 - Privat forslag - 1. (eneste) beh.', u'S',
        u'Privat forslag', u'Regeringsforslag', u'B3',
        u'B1 - Privat forslag', u'B2', u'B1 - Regeringsforslag'
    ]
    proposals = ['Beslutningsforslag', 'Lovforslag']
    GDRAT_abs_path = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'party_member.txt')
    with open(GDRAT_abs_path, 'r') as f:
        party_member = json.load(f)
    print party_member
    print type(party_member)

#    with open('party_member.txt', 'r') as infile:
#        party_member = json.load(infile)

    title, proposing_party, case_category, proposal_type, summary = (
        request.POST['title'],
        request.POST["proposing_party"],
        request.POST['case_category'],
        request.POST['proposal_type'],
        request.POST["summary"]
    )
    #Check that fields are filled out
    for s in [title, proposing_party, case_category, proposal_type, summary]:
        if not s:
            context = {'empty_input': True}
            html = render_to_string('query_folketinget/show_predictions.html', context)
            return HttpResponse(html, content_type='application/javascript')
        else:
            continue
    #The form input is formatted correctly
    input_list, c_category_input, p_type_input = (
        [1 if e == proposing_party else 0 for e in parties],
        [1 if e == html_parser.unescape(case_category) else 0 for e in categories],
        [1 if e == proposal_type else 0 for e in proposals]
    )
    text_input = title + " " + summary
    topic_array = resume_lda.lda_topics(text_input)
    #All the input data is combined in one array
    for inp in (c_category_input, p_type_input, topic_array):
        input_list.extend(inp)
    data_object = np.array(input_list)
    #The votes are predicted
    predictions = utils.predict_votes(data_object)
    final = stats.mode([tup[1] for tup in predictions])
    yes_votes = math.floor(final[1][0]/len(predictions)*100)
    no_votes = math.ceil(100-yes_votes)
    context = {'votes': predictions, 'final': final, 'yes': yes_votes, 'no': no_votes}
    html = render_to_string('query_folketinget/show_predictions.html', context)
    return HttpResponse(html, content_type='application/javascript')

query_folketinget/templates/query_folketinget/base.html
<!DOCTYPE html>
<html>
		<head>
			{% load staticfiles %}
			<meta charset="UTF-8">
			<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>			
			<meta name="viewport" content="width=device-width, initial-scale=1">
			<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
			<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
			<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/jquery.bootstrapvalidator/0.5.0/css/bootstrapValidator.min.css"/>
			<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery.bootstrapvalidator/0.5.0/js/bootstrapValidator.min.js"> </script>
            <script src="{% static "query_folketinget/search_ajax.js" %}"></script>
			<link rel="stylesheet" href="{% static 'query_folketinget/custom.css' %}" />

</head>
		<body>
			<div class="container">
				{% block content %}

				{% endblock content%}
			</div>
	</body>
</html>

query_folketinget/templates/query_folketinget/index.html
{% extends "query_folketinget/base.html" %}

{% load staticfiles %}

{% block content %}
	<div class="row">
		<h2>Predict Folketinget</h2>
		<form method="post" role="form">
			{% csrf_token %}
			<div class="row">
				<div class="col-sm-4">
					<div class="form-group">
						<label>Title</label>
							<input type="text" class="  search-query form-control" id="title" name="title" placeholder="Title" />
					</div>
				</div>
			</div>
			
			<div class="form-group">
				<div class="row">
					<div class="col-sm-4">
						<label for="sel1">Proposing Party</label>
						<select class="form-control" id="proposing_party" name="proposing_party">
							<option></option>
							<option>Venstre</option>
							<option>Socialdemokratiet</option>
							<option>Socialistisk Folkeparti</option>
							<option>Dansk Folkeparti</option>
							<option>Radikale Venstre</option>
							<option>Enhedslisten</option>
							<option>Liberal Alliance</option>
							<option>Det Konservative Folkeparti</option>
						</select>
					</div>
					<div class="col-sm-4">
						<label for="sel2">Case Category</label>
						<select class="form-control" id="case_category" name="case_category">
							<option></option>
							<option>Beretning af almen art</option>
							<option>Alm. del</option>
							<option>FT</option>
							<option>Henvendelser uden bilagsnummer</option>
							<option>Mødesag</option>
							<option>Info-noter</option>
							<option>US</option>
							<option>Alm. del &sect;-markeret</option>
							<option>EU-noter</option>
							<option>B1 - Privat forslag - 1. (eneste) beh.</option>
							<option>S</option>
							<option>Privat forslag</option>
							<option>Regeringsforslag</option>
							<option>B3</option>
							<option>B1 - Privat forslag</option>
							<option>B2</option>
							<option>B1 - Regeringsforslag</option>
						</select>
					</div>
					<div class="col-sm-4">
						<label for="sel3">Proposal Type</label>
						<select class="form-control" id="proposal_type" name="proposal_type">
							<option></option>
							<option>Beslutningsforslag</option>
							<option>Lovforslag</option>
						</select>
					</div>
				</div>
			</div>
			<div class="form-group answer" id="summary">
				<label for="resume">Summary</label>
				<textarea class="form-control" rows="6" id="resume" name="summary"></textarea>
			</div>
			<button id="btn_predict" class="btn btn-danger" type="submit">
                Predict 			
            </button>
		</form>
	</div>
	<div id="prediction_results">
	</div>
<script>
		var csrftoken = '{{ csrf_token }}';
</script>

{% endblock content %}

query_folketinget/templates/query_folketinget/show_predictions.html
{% if empty_input %}
    <div class="alert alert-warning" role="alert">
      <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
      <span class="sr-only">Error:</span>
      All fields must be filled out
    </div>
{% else %}
    {#{{ final }} {{ votes|length }} {{ yes }} {{ no }}#}
    <div class="progress">
       <div class="progress-bar progress-bar-success" role="progressbar" 
          aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" 
          style="width: {{ yes }}%;">
          <span>{{ yes }} %</span>
       </div>
       <div class="progress-bar progress-bar-danger" role="progressbar" 
          aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" 	
          style="width: {{ no }}%;">
          <span>{{ no }} %</span>
       </div>
    </div>
    <table class="table table-striped">
        <thead>
            <tr><th>Name</th><th>Political Party</th><th>Vote</th></tr>
        </thead>
        <tbody>
            {% for v in votes %}
            <tr class="{% ifequal v.1 1 %}success{% else %}danger{% endifequal %}">
                    <td>{{ v.0 }}</td>
                    <td>Enhedslisten</td>
                    <td>{% ifequal v.1 1 %}Yes{% else %}No{% endifequal %}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endif %}

query_folketinget/templates/query_folketinget/test.html
<!-- Copyright 2011 jQuery4u.com -->
<!DOCTYPE html>
<html>
<title>jQuery Function Demo - jQuery4u.com</title>
<head>
<!--
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>	
 
		<script type="text/javascript">
			$(document).ready(function(){
					$.getJSON("https://www.googleapis.com/freebase/v1/text/en/bob_dylan?callback=?", function(data) {
    // Get the element with id summary and set the inner text to the result.
    $('#summary').text(data.result);
		});
	});		
</script> -->
<script src="{% static "/js/search_ajax.js" %}"></script>
{{ data }}
</head>
<body>
<p id="summary"></p> 
</body>
</html>
<!-- Copyright 2011 jQuery4u.com -->

query_folketinget/templates/query_folketinget/working_index.html
{% extends "query_folketinget/base.html" %}

{% load staticfiles %}

{% block content %}
	<div class="row">
		<h2>Predict Folketinget</h2>
		<form role="form" method="post" action="{% url 'query_folketinget:predict' %}">
			{% csrf_token %}
			<div class="row">
				<div class="col-sm-4">
					<div class="form-group">
						<label>Title</label>
							<input type="text" class="  search-query form-control" name="title" placeholder="Title" />
					</div>
				</div>
			</div>
			
			<div class="form-group">
				<div class="row">
					<div class="col-sm-4">
						<label for="sel1">Proposing Party</label>
						<select class="form-control" id="proposing_party" name="proposing_party">
							<option></option>
							<option>Venstre</option>
							<option>Socialdemokratiet</option>
							<option>Socialistisk Folkeparti</option>
							<option>Dansk Folkeparti</option>
							<option>Radikale Venstre</option>
							<option>Enhedslisten</option>
							<option>Liberal Alliance</option>
							<option>Det Konservative Folkeparti</option>
						</select>
					</div>
					<div class="col-sm-4">
						<label for="sel2">Case Category</label>
						<select class="form-control" id="case_category" name="case_category">
							<option></option>
							<option>Beretning af almen art</option>
							<option>Alm. del</option>
							<option>FT</option>
							<option>Henvendelser uden bilagsnummer</option>
							<option>Mødesag</option>
							<option>Info-noter</option>
							<option>US</option>
							<option>Alm. del &sect;-markeret</option>
							<option>EU-noter</option>
							<option>B1 - Privat forslag - 1. (eneste) beh.</option>
							<option>S</option>
							<option>Privat forslag</option>
							<option>Regeringsforslag</option>
							<option>B3</option>
							<option>B1 - Privat forslag</option>
							<option>B2</option>
							<option>B1 - Regeringsforslag</option>
						</select>
					</div>
					<div class="col-sm-4">
						<label for="sel3">Proposal Type</label>
						<select class="form-control" id="proposal_type" name="proposal_type">
							<option></option>
							<option>Beslutningsforslag</option>
							<option>Lovforslag</option>
						</select>
					</div>
				</div>
			</div>
			<div class="form-group answer" id="summary">
				<label for="resume">Summary</label>
				<textarea class="form-control" rows="6" id="resume" name="summary">
				</textarea>
			</div>
			<button id="" class="btn btn-danger" type="submit">
				Predict <!--<span class=" glyphicon glyphicon-search"></span>-->
			</button>
		</form>
	</div>
	<div id="prediction_results">
		{% include "query_folketinget/show_predictions.html" %}
	</div>
{% endblock content %}